### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by cescoferraro** [karlvr/storybook-preset-less#1] opened 2022-01-05 12:15 UTC
Every time I try to import a less file, it breaks storybook with

```
ERROR in ./packages/separation/src/HelixField/style.less
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/cescoferraro/go/src/github.com/exome/exome-components/node_modules/style-loader/dist/index.js:19:24)
 @ ./packages/separation/src/HelixField/index.js 56:0-23
 @ ./packages/separation/src/SeparationMain.js
 @ ./packages/separation/src/SeparationContainer.js
 @ ./packages/separation/src/CompetitiveSepatationManager.tsx
 @ ./packages/separation/src/CompetitiveSepatationManager.stories.tsx
 @ ./packages sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

```

<img width="1757" alt="Screen Shot 2022-01-05 at 09 15 00" src="https://user-images.githubusercontent.com/6259987/148216136-0b559868-d84b-4059-9ff0-6a99654b9791.png">

**Comment by tekstop** [comment] 2022-02-15 09:55
Same here

**Comment by rublev** [comment] 2022-02-18 08:17
same ahhh

**Comment by WangShuXian6** [comment] 2022-03-17 05:37
Reducing the less-loader version to 7.2.0 or lower will temporarily fix the problem.

The problem is due to the loader being updated with the options option for webpack5

将 less-loader 版本降至7.2.0或更低可以临时解决该问题。

该问题是由于 loader 为了适配 webpack5 而升级 更新了 options 选项

**Comment by karlvr** [comment] 2022-08-25 08:52
I'm closing this as I think perhaps it's a `less-loader` issue rather than this module?

**Closed as completed by karlvr** 2022-08-25 08:52 UTC
